export const CART_ACTION_TYPES = {
    TOGGLE_DROPDOWN: 'cart/TOGGLE_DROPDOWN',
    SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
    SET_CARTCOUNT: 'cart/SET_CARTCOUNT',
    SET_CART_TOTAL: 'cart/SET_CART_TOTAL',
};
